name: Check pre-commit Hooks

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pre-commit and hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit hooks
        run: pre-commit run -a
