name: Check Commit Messages

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: agenthunt/conventional-commit-checker-action@v1.0.0
